### ISSUE TITLE
Add "percent-open-reason" to vent states

### ISSUE THREAD

**Issue by FlyingDiver** [FlyingDiver/Indigo-Flair#3]
If you get around to it, any chance you could have the "percent-open-reason" show up on the device details of the vents? That is flair telling you WHY it is open or closed. Useful data for reporting or heads up purposes without drilling down 3 layers in the flair app.

"percent-open-reason": "This room is cooling. Vent will close when the room is below 72.0F.",

_Originally posted by @brookwatson in https://github.com/FlyingDiver/Indigo-Flair/issues/2#issuecomment-882104368_

**Comment by FlyingDiver** [comment]
In 0.0.7

**Comment by brookwatson** [comment]
Confirmed to work in 0.0.7. Thanks Joe.

![Screen Shot 2021-07-22 at 12 16 30 PM](https://user-images.githubusercontent.com/22889794/126688828-9b349698-9b7b-4143-8f63-617dbb7d294c.png)
